= Red Hat JBoss EAP Administration I
:navtitle: Home

== Introduction

Welcome to this quick course on the _Basics of Red Hat JBoss EAP Administration_.
This course is the `second` in a series of `four` courses about Red Hat JBoss EAP:

. Introduction to Red Hat JBoss EAP
.. https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering%3D59719403[For Red Hat Associates^]
.. https://training-lms.redhat.com/sso/saml/auth/rhopen?RelayState=deeplinkoffering%3D59719502[For Red Hat Partners^]
. *Red Hat JBoss EAP Administration I  (_This course_)*
. https://redhatquickcourses.github.io/eap-admin2[Red Hat JBoss EAP Administration II^]
. https://demo.redhat.com/catalog?search=eap+8&item=babylon-catalog-prod%2Fsandboxes-gpte.jboss-eap-migration.prod[Migrating to Red Hat JBoss EAP 8^]

This course covers the install and uninstall process for Red Hat JBoss EAP 8. You also learn about the basics of EAP 8 configuration, how to configure database connectivity, and deploy basic web applications.

NOTE: The hands-on labs for this course have been tested on *JBoss EAP 8.0*. The labs should mostly work in minor update releases of EAP 8. If you encounter any issues, please open a GitHub issue in the course repository.

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Ravi Srinivasan
* Yogita Soni
* Ashish Shah
* Rutuja Deshmukh
* Abhijit Humbe

== Classroom Environment

This course does *NOT* have JBoss EAP 8 pre-installed. You will install and configure a basic JBoss EAP 8 instance in this course, and then continue using this instance in labs throughout this course. Other courses may instruct you to install more instances to avoid overwriting configuration files from other exercises.

This training includes detailed lab instructions for learners to follow. Please note that there is no separate lab environment provided. Learners are expected to execute the instructions on their local machines (using VMs) or in their preferred development environments.

NOTE: We are planning to provide a classroom environment for Red Hat associates and select Red Hat partners on the Red Hat Demo Platform (RHDP). This is a work in progress. Classroom links will be updated here as and when the classroom is ready. Leave a https://github.com/RedHatQuickCourses/eap-admin1/issues/16#issue-2300120102[comment or +1 this issue^] to up vote. Until then, we recommend using your own servers or VMs to run the hands-on labs in this learning path.

For the hands-on labs in this course, you need to provision the following:

* 2 RHEL 9 or CentOS Stream 9 VMs - each with at least 8 vCPU, 16GB RAM, 2 NICs and 80GB hard disk

== Prerequisites

* Basic knowledge of Linux administration
* Basic knowledge of Java and deploying applications on the Java Virtual Machine (JVM)
* Sign up for a free https://developer.redhat.com[Red Hat Developer^] account if you don't have one.

== Objectives

The overall objectives of this course include:

* Install and uninstall Red Hat JBoss EAP
* Perform basic configuration of JBoss EAP
* Configure the web, messaging, logging and database subsystems
