= Red Hat JBoss EAP Administration I
:navtitle: Home

== Introduction

Welcome to this quick course on the _Basics of Red Hat JBoss EAP Administration_.
This course is the `second` in a series of `seven` courses about Red Hat JBoss EAP:

1. Introduction to Red Hat JBoss EAP (_Under Development_)
2. *Red Hat JBoss EAP Administration I  (_This course_)*
3. Red Hat JBoss EAP Administration II (_Under Development_)
4. Migrating to Red Hat JBoss EAP 8 (_Under Development_)
5. Red Hat JBoss EAP 8 Deployment in Public Cloud Infrastructures (_Under Development_)
6. Developing Applications for Red Hat JBoss EAP 8 (_Under Development_)
7. Red Hat JBoss EAP 8 Workshop (_Under Development_)

This course covers the install and uninstall process for Red Hat JBoss EAP 8. You also learn about the basics of EAP 8 configuration, how to configure database connectivity, and deploy basic web applications.

NOTE: The hands-on labs for this course have been tested on *JBoss EAP 8.0*. The labs should mostly work in minor update releases of EAP 8. If you encounter any issues, please open a GitHub issue in the course repository.

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Ravi Srinivasan
* Yogita Soni
* Ashish Shah
* Rutuja Deshmukh
* Abhijit Humbe

== Classroom Environment

This course does *NOT* have JBoss EAP 8 pre-installed. You will install and configure a basic JBoss EAP 8 instance in this course, and then continue using this instance in labs throughout this course. Other courses may instruct you to install more instances to avoid overwriting configuration files from other exercises.

This training includes detailed lab instructions for learners to follow. Please note that there is no separate lab environment provided; learners are expected to execute the instructions on their local machines or in their preferred development environments.

[NOTE]
====
There are plans to create a classroom environment in Red Hat Demo Platform (RHDP). Leave a https://github.com/RedHatQuickCourses/eap-admin1/issues/16#issue-2300120102[comment or +1 this issue^] to upvote.

====

=== Infrastructure Details:

Learner would need single RHEL 9 instance with at least:

* 8 vCPU
* 16GB RAM
* 2 NICs
* 80GB hard disk

== Prerequisites

* Basic knowledge of Linux administration
* Basic knowledge of Java and deploying applications on the Java Virtual Machine (JVM)
* Sign up for a free https://developer.redhat.com[Red Hat Developer^] account if you don't have one.

== Objectives

The overall objectives of this course include:

* Install and uninstall Red Hat JBoss EAP
* Perform basic configuration of JBoss EAP