= Red Hat JBoss EAP 8 CLI

* Red Hat JBoss EAP 8 employs XML files for configuration, offering three methods:

. **Management console**: Red Hat JBoss EAP 8 offers an easy to use web console to configure various subsystems of JBoss EAP.
. **Management CLI**: A command-line tool for configuration and scripting.
. **Manual XML editing**: It's typically advised to avoid directly modifying XML configuration files, although there are situations where it may become necessary.

Benefits of the management CLI include GUI-free server management and scriptable task execution, while offering comprehensive configuration control compared to the console.

== Executing Commands

* Run the `jboss-cli.sh` script to start the management CLI from the bin directory of the JBoss EAP installation.

* Without arguments, it runs in disconnected mode:
+
[subs="+quotes,+macros"]
----
[vagrant@server bin]$ $JBOSS_HOME/bin/jboss-cli.sh
You are disconnected at the moment. Type 'connect' to connect to the server or 'help' for the list of supported commands.
[disconnected /]
----

* The connect command connects to the default host (localhost) and port (9990) if no arguments are provided:
+
[subs="+quotes,+macros"]
----
[disconnected /] connect localhost:9990
Authenticating against security realm: ManagementRealm
Username: XXXXXXX
Password: XXXXXXX
[standalone@localhost:9990 /]
----

* To automatically connect, use the `--connect` or `-c` argument:
+
[subs="+quotes,+macros"]
----
[vagrant@server bin]$ sudo -u jboss $JBOSS_HOME/bin/jboss-cli.sh --connect
[standalone@localhost:9990 /]

[vagrant@server bin]$ sudo -u jboss $JBOSS_HOME/bin/jboss-cli.sh -c
[standalone@localhost:9990 /]
----

* For connecting to a different host, use the --controller argument:
+
[subs="+quotes,+macros"]
----
[vagrant@server bin]$ $JBOSS_HOME/bin/jboss-cli.sh --connect --controller=ip:port
----

* Optionally you can use --user and --password to pass credentials if needed.
+
[subs="+quotes,+macros"]
----
[vagrant@server bin]$ $JBOSS_HOME/bin/jboss-cli.sh --connect  \
--user=XXXXX --password=XXXXX
----

=== Red Hat JBoss EAP 8 Commands

* The management CLI for Red Hat JBoss EAP 8 offers user-friendly commands that translate into operation requests.

* Basic supported commands include:
. **connect**: Connect to the server or domain controller.
. **cn or cd**: Change the current node path.
. **ls**: List contents of the node path.
. **help**: Display the help page.
. **history**: Manage history expansion.
. **version**: Print version and environment information.
. **pwn or pwd**: Print the current working node.
. **data-source**: Manage resources of the /subsystem=datasources/data-source type.
. **deploy**: Deploy an application.
. **undeploy**: Undeploy an application.
. **exit or quit**: Quit the management CLI.

=== Operations

* Operations are a low level way to manage the JBoss EAP server.
* Operations in the JBoss EAP 8 server management CLI follow this format:
+
[subs="+quotes,+macros"]
----
[node] :operation_name [ parameters ] [ headers ]
----

* Format explaination:
. The node is a key/value pair representing the target resource address.
. You define the operation name with optional parameters.
. Common operations include -
.. **:read-resource** for reading attributes. Eg:
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] :read-resource
{
    "outcome" => "success",
    "result" => {
        "management-major-version" => 22,
        "management-micro-version" => 0,
...output_omitted...
----

.. **:reload** for server restart. The Java process is not restarted.
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] :reload
{
    "outcome" => "success",
    "result" => undefined
}
----

.. **:remove** for node deletion
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] /subsystem=datasources/data-source=myDataSource:remove
{
    "outcome" => "success",
    "response-headers" => {
        "operation-requires-reload" => true,
        "process-state" => "reload-required"
    }
}
----
Replace myDataSource with the name of the data source you want to remove.

=== Tab Completion
* Tab completion displays available commands at any point in a command.

* You can enter /. Then, press Tab to view all possible values after the / character.
+
[subs="+quotes,+macros"]
----
[vagrant@server ~]$ $JBOSS_HOME/bin/jboss-cli.sh --connect  \
--user=XXXXX --password=XXXXX
[standalone@localhost:9990 /] /
core-service          extension             socket-binding-group
deployment            interface             subsystem
deployment-overlay    path                  system-property
----

* Scripts can be executed using text files, and batch commands support multiple operations in one atomic unit, ensuring rollback if any operation fails.
* External scripts can integrate with the CLI using the `--command` or `--commands` attribute.

[Tip]
====
* Tip:
. Start typing interface after the / character, and press Tab.
. The management CLI not only completes the interface sub-level, but it adds an equals sign, because an equals sign is the only possible value after /interface.
. Press Tab again and all the interfaces display:
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] /interface=
management  public
----
====

=== Running a Management CLI Script File

* The Red Hat JBoss EAP 8 supports script files for CLI management, aiding in repetitive tasks.

* For instance, you can configure a data source and test its connection by create a script as shown below:
+
[subs="+quotes,+macros"]
----
[vagrant@server ~]$ *sudo vi /opt/create-datasource.cli*
/subsystem=datasources/data-source=appDs:add(jndi-name=java:jboss/datasources/appDS,driver-name=h2,user-name=jb248,password=jb248,connection-url="jdbc:h2:mem:app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE")
/subsystem=datasources/data-source=appDs:test-connection-in-pool
----

* Execute script `/opt/create-datasource.cli` as shown below:
+
[subs="+quotes,+macros"]
----
[vagrant@server ~]$ sudo -u jboss /opt/EAP-8.0.0/bin/jboss-cli.sh \
--connect --controller=localhost:9990 \
--file=/opt/create-datasource.cli
{
    "outcome" => "success",
    "response-headers" => {"process-state" => "reload-required"}
}
{
    "outcome" => "success",
    "result" => [true],
    "response-headers" => {"process-state" => "reload-required"}
}
----

* Also, you can execute multiple commands using the `--commands` attribute:
+
[subs="+quotes,+macros"]
----
[vagrant@server ~]$ sudo -u jboss /opt/EAP-8.0.0/bin/jboss-cli.sh \
--connect --controller=localhost:9990 \
--commands="cd /subsystem=datasources, ls"
data-source
jdbc-driver
xa-data-source
installed-drivers=[{"driver-name" => "h2","deployment-name" => undefined,"driver-module-name" => "com.h2database.h2","module-slot" => "main","driver-datasource-class-name" => "","driver-xa-datasource-class-name" => "org.h2.jdbcx.JdbcDataSource","datasource-class-info" => [{"org.h2.jdbcx.JdbcDataSource" => {"URL" => "java.lang.String","description" => "java.lang.String","loginTimeout" => "int","password" => "java.lang.String","url" => "java.lang.String","user" => "java.lang.String"}}],"driver-class-name" => "org.h2.Driver","driver-major-version" => 2,"driver-minor-version" => 1,"jdbc-compliant" => true}]
----

== Lab: Executing Red Hat JBoss EAP 8 commands

**Outcome**: In this lab, you execute different JBoss EAP 8 commands.

* Connect to the server or domain controller.
+
[subs="+quotes,+macros"]
----
[vagrant@server bin]$ $JBOSS_HOME/bin/jboss-cli.sh
[disconnected /] connect
[standalone@localhost:9990 /]
----

* Change the current node path to `user.home` as shown in below command.
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] cd path=user.home
[standalone@localhost:9990 /] cd /
[standalone@localhost:9990 /]
----

* List contents of current node path.
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] cd path=user.home
[standalone@localhost:9990 path=user.home] ls
name=user.home         read-only=true
path=/home/jboss       relative-to=undefined
----

* Display the help page.
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] help
SYNOPSIS
    help ( [<command or operation name>] | [--commands] )
...output_omitted...
----

* Display the history of commands executed so far.
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] history
help
...output_omitted...
----

* Print version and environment information.
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] version
JBoss Admin Command-line Interface
JBOSS_HOME: /opt/EAP-8.0.0
Release: 21.0.5.Final-redhat-00001
Product: JBoss EAP 8.0 Update 1.0
JAVA_HOME: null
java.version: 17.0.6
java.vm.vendor: Red Hat, Inc.
java.vm.version: 17.0.6+10-LTS
os.name: Linux
os.version: 5.14.0-284.25.1.el9_2.x86_64
----

* Print the current working node.
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] cd path=user.home
[standalone@localhost:9990 path=user.home] pwd
/path=user.home
----

* Manage resources of the /subsystem=datasources/data-source type.

. Create a data source named "myDataSource" with the following configuration:

... **JNDI name**: java:jboss/datasources/myDataSource
... **Driver name**: h2
... **Username**: myUsername
... **Password**: myPassword
... **Connection URL**: jdbc:h2:mem:test

. Add the data source:
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] /subsystem=datasources/data-source=myDataSource:add(jndi-name=java:jboss/datasources/myDataSource, driver-name=h2, user-name=myUsername, password=myPassword, connection-url="jdbc:h2:mem:test")
{"outcome" => "success"}
----

. Test the connection:
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] /subsystem=datasources/data-source=myDataSource:test-connection-in-pool
{
    "outcome" => "success",
    "result" => [true]
}
----

. This will create the data source and test the connection to ensure it's functioning correctly. You can adjust the configuration parameters as needed for your specific use case.

* Quit the management CLI.
+
[subs="+quotes,+macros"]
----
[standalone@localhost:9990 /] exit
----